/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.totpSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.totpConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.totpVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["company.index"];
        put?: never;
        post: operations["company.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/companies/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["company.registerOwn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/companies/{company}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["company.show"];
        put?: never;
        post?: never;
        delete: operations["company.destroy"];
        options?: never;
        head?: never;
        patch: operations["company.update"];
        trace?: never;
    };
    "/v1/companies/{company}/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["company.switch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lead.index"];
        put?: never;
        post: operations["lead.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["package.index"];
        put?: never;
        post: operations["package.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/packages/{package}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["package.show"];
        put?: never;
        post?: never;
        delete: operations["package.destroy"];
        options?: never;
        head?: never;
        patch: operations["package.update"];
        trace?: never;
    };
    "/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["payment.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{payment}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payment.submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{payment}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payment.confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{payment}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payment.reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["platformSetting.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["platformSetting.update"];
        trace?: never;
    };
    "/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscription.index"];
        put?: never;
        post: operations["subscription.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BillingPeriod
         * @enum {string}
         */
        BillingPeriod: "monthly" | "yearly" | "one_time";
        /** CaptureLeadRequest */
        CaptureLeadRequest: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string | null;
            company_name?: string | null;
            source?: string;
        };
        /** CompanyResource */
        CompanyResource: {
            id: string;
            name: string;
            name_kh: string | null;
            registration_no: string | null;
            employee_count: number | null;
            bypass_flags: unknown[];
            industry_code: string;
            country_code: string;
            status: components["schemas"]["CompanyStatus"];
            compliance_score: number;
            default_locale: string;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * CompanyStatus
         * @enum {string}
         */
        CompanyStatus: "active" | "suspended" | "inactive";
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        /** LeadResource */
        LeadResource: {
            id: string;
            company_id: string | null;
            name: string;
            email: string;
            phone: string | null;
            company_name: string | null;
            source: string;
            /** Format: date-time */
            created_at: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** PackageResource */
        PackageResource: {
            id: string;
            name: string;
            name_kh: string | null;
            description: string | null;
            price_cents: number;
            billing_period: components["schemas"]["BillingPeriod"];
            is_active: boolean;
            sort_order: number;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "stripe" | "manual_bank_transfer";
        /** PaymentResource */
        PaymentResource: {
            id: string;
            company_id: string;
            subscription_id: string;
            amount_cents: number;
            currency: string;
            method: components["schemas"]["PaymentMethod"];
            status: components["schemas"]["PaymentStatus"];
            gateway_reference: string | null;
            /** Format: date-time */
            submitted_at: string | null;
            /** Format: date-time */
            confirmed_at: string | null;
            /** Format: date-time */
            created_at: string | null;
        };
        /**
         * PaymentStatus
         * @enum {string}
         */
        PaymentStatus: "pending" | "awaiting_confirmation" | "confirmed" | "failed" | "rejected";
        /** PlatformSettingResource */
        PlatformSettingResource: {
            key: string;
            value: unknown[];
            group: string;
            updated_by: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            locale?: "en" | "kh";
            password_confirmation: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            token: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirmation: string;
        };
        /** StoreCompanyRequest */
        StoreCompanyRequest: {
            name: string;
            name_kh?: string | null;
            registration_no?: string | null;
            employee_count?: number | null;
            industry_code: string;
            country_code?: string;
            /** @enum {string} */
            default_locale?: "en" | "kh";
        };
        /** StorePackageRequest */
        StorePackageRequest: {
            name: string;
            name_kh?: string | null;
            description?: string | null;
            price_cents: number;
            /** @enum {string} */
            billing_period?: "monthly" | "yearly" | "one_time";
            is_active?: boolean;
            sort_order?: number;
        };
        /** SubscribeRequest */
        SubscribeRequest: {
            package_id: string;
            /** @enum {string} */
            method: "stripe" | "manual_bank_transfer";
        };
        /** SubscriptionResource */
        SubscriptionResource: {
            id: string;
            company_id: string;
            package?: components["schemas"]["PackageResource"];
            status: components["schemas"]["SubscriptionStatus"];
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            created_at: string | null;
        };
        /**
         * SubscriptionStatus
         * @enum {string}
         */
        SubscriptionStatus: "pending" | "active" | "expired" | "cancelled";
        /** TotpVerifyRequest */
        TotpVerifyRequest: {
            code: string;
        };
        /** UpdateCompanyRequest */
        UpdateCompanyRequest: {
            name?: string;
            name_kh?: string | null;
            registration_no?: string | null;
            industry_code?: string;
            country_code?: string;
            /** @enum {string} */
            default_locale?: "en" | "kh";
        };
        /** UpdatePackageRequest */
        UpdatePackageRequest: {
            name?: string;
            name_kh?: string | null;
            description?: string | null;
            price_cents?: number;
            /** @enum {string} */
            billing_period?: "monthly" | "yearly" | "one_time";
            is_active?: boolean;
            sort_order?: number;
        };
        /** UpdatePlatformSettingRequest */
        UpdatePlatformSettingRequest: {
            value: string;
            group?: string;
        };
        /** UserResource */
        UserResource: {
            id: string;
            name: string;
            email: string;
            locale: string;
            status: components["schemas"]["UserStatus"];
            current_company_id: string | null;
            /**
             * @description A user can belong to more than one company (§0.7 of the MVP proposal) —
             *     the frontend's company switcher lists these, current_company_id says which
             *     one is active. Lazy-loads if not already eager-loaded; this resource wraps
             *     a single user, never a collection, so the extra query is a one-off, not N+1.
             */
            companies: components["schemas"]["CompanyResource"][];
            roles: Record<string, never>;
            /** Format: date-time */
            email_verified_at: string | null;
            totp_enabled: boolean;
            totp_required: boolean;
            /** Format: date-time */
            created_at: string | null;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "inactive" | "suspended";
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["UserResource"];
                            token: string;
                            totp_required: boolean;
                        };
                        meta: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user: components["schemas"]["UserResource"];
                            token: string;
                            totp_required: boolean;
                        };
                        meta: string[];
                    } | {
                        data: {
                            user: components["schemas"]["UserResource"];
                            token: string;
                            totp_required: boolean;
                            totp_confirmed: boolean;
                        };
                        meta: string[];
                    };
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Your account has been suspended.";
                        errors: string[];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.forgotPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Always return 200 — never leak whether the email exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @constant */
                            message: "If that email exists, a reset link has been sent.";
                        };
                        meta: string[];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            message: unknown;
                        };
                        meta: string[];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                        meta: string[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.totpSetup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            secret: string;
                            qr_code_url: string;
                        };
                        meta: string[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.totpConfirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            token: string;
                            /** @constant */
                            message: "Two-factor authentication enabled.";
                        };
                        meta: string[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.totpVerify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            token: string;
                            /** @constant */
                            message: "Two-factor authentication verified.";
                        };
                        meta: string[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "company.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CompanyResource"][];
                        meta: {
                            pagination: {
                                total: number;
                                per_page: number;
                                current_page: number;
                                last_page: number;
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "company.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCompanyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CompanyResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "company.registerOwn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCompanyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            company: components["schemas"]["CompanyResource"];
                            user: components["schemas"]["UserResource"];
                        };
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "company.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The company ID */
                company: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CompanyResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "company.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The company ID */
                company: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "company.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The company ID */
                company: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateCompanyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CompanyResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "company.switch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The company ID */
                company: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "lead.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LeadResource"][];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "lead.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureLeadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LeadResource"];
                        meta: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "package.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PackageResource"][];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "package.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorePackageRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PackageResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "package.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The package ID */
                package: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PackageResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "package.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The package ID */
                package: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "package.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The package ID */
                package: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePackageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PackageResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "payment.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PaymentResource"][];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "payment.submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The payment ID */
                payment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PaymentResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "payment.confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The payment ID */
                payment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PaymentResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "payment.reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The payment ID */
                payment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PaymentResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "platformSetting.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlatformSettingResource"][];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "platformSetting.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlatformSettingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlatformSettingResource"];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "subscription.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SubscriptionResource"][];
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "subscription.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            subscription: components["schemas"]["SubscriptionResource"];
                            payment: components["schemas"]["PaymentResource"];
                            gateway_data: {
                                [key: string]: unknown;
                            };
                        };
                        meta: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
}
